# Translations template for patron.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the patron project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: patron 2015.1.dev152\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-31 06:16+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: patron/crypto.py:455
msgid "Failed to write inbound.csr"
msgstr ""

#: patron/exception.py:124
msgid "Exception in string format operation"
msgstr ""

#: patron/hooks.py:93
#, python-format
msgid "Fatal Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr ""

#: patron/hooks.py:99
#, python-format
msgid "Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr ""

#: patron/notifications.py:150 patron/notifications.py:189
msgid "Failed to send state update notification"
msgstr ""

#: patron/notifications.py:293
msgid "Failed to get nw_info"
msgstr ""

#: patron/quota.py:1368
#, python-format
msgid "Failed to commit reservations %s"
msgstr ""

#: patron/quota.py:1392
#, python-format
msgid "Failed to roll back reservations %s"
msgstr ""

#: patron/service.py:300
msgid "Service error occurred during cleanup_host"
msgstr ""

#: patron/service.py:317
#, python-format
msgid "Temporary directory is invalid: %s"
msgstr ""

#: patron/utils.py:436
#, python-format
msgid "Invalid server_string: %s"
msgstr ""

#: patron/utils.py:711
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: patron/version.py:62
#, python-format
msgid "Failed to load %(cfgfile)s: %(ex)s"
msgstr ""

#: patron/wsgi.py:144
#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr ""

#: patron/wsgi.py:213
#, python-format
msgid "Failed to start %(name)s on %(host)s:%(port)s with SSL support"
msgstr ""

#: patron/wsgi.py:535
#, python-format
msgid "Couldn't lookup app: %s"
msgstr ""

#: patron/api/ec2/__init__.py:95
msgid "FaultWrapper error"
msgstr ""

#: patron/api/ec2/__init__.py:299
#, python-format
msgid "Keystone failure: %s"
msgstr ""

#: patron/api/ec2/__init__.py:555
#, python-format
msgid "Unexpected %(ex_name)s raised: %(ex_str)s"
msgstr ""

#: patron/api/ec2/__init__.py:582
#, python-format
msgid "Environment: %s"
msgstr ""

#: patron/api/metadata/handler.py:161 patron/api/metadata/handler.py:169
#, python-format
msgid "Failed to get metadata for ip: %s"
msgstr ""

#: patron/api/metadata/handler.py:222 patron/api/metadata/handler.py:230
#, python-format
msgid "Failed to get metadata for instance id: %s"
msgstr ""

#: patron/api/openstack/__init__.py:93
#, python-format
msgid "Caught error: %s"
msgstr ""

#: patron/api/openstack/common.py:139
#, python-format
msgid ""
"status is UNKNOWN from vm_state=%(vm_state)s task_state=%(task_state)s. "
"Bad upgrade or db corrupted?"
msgstr ""

#: patron/api/openstack/extensions.py:196
#: patron/api/openstack/compute/plugins/__init__.py:46
msgid "Exception loading extension"
msgstr ""

#: patron/api/openstack/extensions.py:493
msgid "Unexpected exception in API method"
msgstr ""

#: patron/api/openstack/wsgi.py:518
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:69
#, python-format
msgid "Compute.api::pause %s"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:91
#, python-format
msgid "Compute.api::unpause %s"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:113
#, python-format
msgid "compute.api::suspend %s"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:135
#, python-format
msgid "compute.api::resume %s"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:159
msgid "Error in migrate"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:178
#, python-format
msgid "Compute.api::reset_network %s"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:197
#, python-format
msgid "Compute.api::inject_network_info %s"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:214
#, python-format
msgid "Compute.api::lock %s"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:233
#, python-format
msgid "Compute.api::unlock %s"
msgstr ""

#: patron/api/openstack/compute/contrib/admin_actions.py:388
#, python-format
msgid "Compute.api::resetState %s"
msgstr ""

#: patron/api/openstack/compute/contrib/multinic.py:77
#, python-format
msgid "Unable to find address %r"
msgstr ""

#: patron/api/openstack/compute/contrib/os_tenant_networks.py:78
#: patron/api/openstack/compute/plugins/v3/tenant_networks.py:74
msgid "Failed to get default networks"
msgstr ""

#: patron/api/openstack/compute/contrib/os_tenant_networks.py:118
#: patron/api/openstack/compute/plugins/v3/tenant_networks.py:117
msgid "Failed to update usages deallocating network."
msgstr ""

#: patron/api/openstack/compute/contrib/server_groups.py:157
#: patron/api/openstack/compute/plugins/v3/server_groups.py:100
msgid "Failed to update usages deallocating server group"
msgstr ""

#: patron/cells/messaging.py:205
msgid "Error processing message locally"
msgstr ""

#: patron/cells/messaging.py:414
msgid "Error locating next hop for message"
msgstr ""

#: patron/cells/messaging.py:440
#, python-format
msgid "Failed to send message to cell: %(next_hop)s"
msgstr ""

#: patron/cells/messaging.py:518
msgid "Error locating next hops for message"
msgstr ""

#: patron/cells/messaging.py:537
msgid "Error sending message to next hops."
msgstr ""

#: patron/cells/messaging.py:554
msgid "Error waiting for responses from neighbor cells"
msgstr ""

#: patron/cells/messaging.py:1889
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: patron/cells/rpcapi.py:409
msgid "Failed to notify cells of BDM update/create."
msgstr ""

#: patron/cells/rpcapi.py:425
msgid "Failed to notify cells of BDM destroy."
msgstr ""

#: patron/cells/scheduler.py:198
#, python-format
msgid "Couldn't communicate with cell '%s'"
msgstr ""

#: patron/cells/scheduler.py:202
msgid "Couldn't communicate with any cells"
msgstr ""

#: patron/cells/scheduler.py:245
#, python-format
msgid "Error scheduling instances %(instance_uuids)s"
msgstr ""

#: patron/cells/state.py:179
msgid "DB error"
msgstr ""

#: patron/cells/state.py:365
#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capabilities"
msgstr ""

#: patron/cells/state.py:380
#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capacities"
msgstr ""

#: patron/cmd/all.py:63
#, python-format
msgid "Failed to load %s-api"
msgstr ""

#: patron/cmd/all.py:69 patron/cmd/all.py:92
#, python-format
msgid "Failed to load %s"
msgstr ""

#: patron/cmd/compute.py:50
#, python-format
msgid "No db access allowed in patron-compute: %s"
msgstr ""

#: patron/cmd/dhcpbridge.py:108
#, python-format
msgid "No db access allowed in patron-dhcpbridge: %s"
msgstr ""

#: patron/cmd/dhcpbridge.py:140
msgid "Environment variable 'NETWORK_ID' must be set."
msgstr ""

#: patron/cmd/network.py:50
#, python-format
msgid "No db access allowed in patron-network: %s"
msgstr ""

#: patron/compute/api.py:630
msgid "Failed to set instance name using multi_instance_display_name_template."
msgstr ""

#: patron/compute/api.py:1532
msgid ""
"Something wrong happened when trying to delete snapshot from shelved "
"instance."
msgstr ""

#: patron/compute/api.py:3251
#, python-format
msgid "Instance compute service state on %s expected to be down, but it was up."
msgstr ""

#: patron/compute/api.py:3981
msgid "Failed to update usages deallocating security group"
msgstr ""

#: patron/compute/flavors.py:188
#, python-format
msgid "Instance type %s not found for deletion"
msgstr ""

#: patron/compute/manager.py:398
#, python-format
msgid "Error while trying to clean up image %s"
msgstr ""

#: patron/compute/manager.py:832
msgid "Failed to check if instance shared"
msgstr ""

#: patron/compute/manager.py:914 patron/compute/manager.py:992
msgid "Failed to complete a deletion"
msgstr ""

#: patron/compute/manager.py:959
msgid "Failed to cleanup snapshot."
msgstr ""

#: patron/compute/manager.py:1041
msgid "Failed to unpause instance"
msgstr ""

#: patron/compute/manager.py:1053
msgid "Failed to stop instance"
msgstr ""

#: patron/compute/manager.py:1065
msgid "Failed to start instance"
msgstr ""

#: patron/compute/manager.py:1076
msgid "Vifs plug failed"
msgstr ""

#: patron/compute/manager.py:1096
msgid "Failed to revert crashed migration"
msgstr ""

#: patron/compute/manager.py:1537
msgid "Failed to dealloc network for deleted instance"
msgstr ""

#: patron/compute/manager.py:1558
msgid "Failed to dealloc network for failed instance"
msgstr ""

#: patron/compute/manager.py:1585
#, python-format
msgid "Error: %s"
msgstr ""

#: patron/compute/manager.py:1634 patron/compute/manager.py:3882
msgid "Error trying to reschedule"
msgstr ""

#: patron/compute/manager.py:1742
#, python-format
msgid "Instance failed network setup after %(attempts)d attempt(s)"
msgstr ""

#: patron/compute/manager.py:1933
msgid "Instance failed block device setup"
msgstr ""

#: patron/compute/manager.py:1959 patron/compute/manager.py:2404
#: patron/compute/manager.py:4441
msgid "Instance failed to spawn"
msgstr ""

#: patron/compute/manager.py:2232
msgid "Unexpected build failure, not rescheduling build."
msgstr ""

#: patron/compute/manager.py:2300 patron/compute/manager.py:2357
msgid "Failed to allocate network(s)"
msgstr ""

#: patron/compute/manager.py:2389
msgid "Failure prepping block device"
msgstr ""

#: patron/compute/manager.py:2430
msgid "Failed to deallocate networks"
msgstr ""

#: patron/compute/manager.py:2478
msgid "Failed to deallocate network for instance."
msgstr ""

#: patron/compute/manager.py:2690 patron/compute/manager.py:4077
#: patron/compute/manager.py:6332
msgid "Setting instance vm_state to ERROR"
msgstr ""

#: patron/compute/manager.py:2923 patron/compute/manager.py:5386
#, python-format
msgid "Failed to get compute_info for %s"
msgstr ""

#: patron/compute/manager.py:3115
#, python-format
msgid "Cannot reboot instance: %s"
msgstr ""

#: patron/compute/manager.py:3351
msgid "set_admin_password failed"
msgstr ""

#: patron/compute/manager.py:3440
msgid "Error trying to Rescue Instance"
msgstr ""

#: patron/compute/manager.py:3538
#, python-format
msgid "Migration %s is not found during confirmation"
msgstr ""

#: patron/compute/manager.py:4083
msgid "Failed to rollback quota for failed finish_resize"
msgstr ""

#: patron/compute/manager.py:4738
#, python-format
msgid "Failed to attach %(volume_id)s at %(mountpoint)s"
msgstr ""

#: patron/compute/manager.py:4782
#, python-format
msgid "Failed to detach volume %(volume_id)s from %(mp)s"
msgstr ""

#: patron/compute/manager.py:4861
#, python-format
msgid "Failed to swap volume %(old_volume_id)s for %(new_volume_id)s"
msgstr ""

#: patron/compute/manager.py:4868
#, python-format
msgid "Failed to connect to volume %(volume_id)s with volume at %(mountpoint)s"
msgstr ""

#: patron/compute/manager.py:4957
#, python-format
msgid "allocate_port_for_instance returned %(ports)s ports"
msgstr ""

#: patron/compute/manager.py:5183
#, python-format
msgid "Pre live migration failed at %s"
msgstr ""

#: patron/compute/manager.py:5562
msgid "An error occurred while refreshing the network cache."
msgstr ""

#: patron/compute/manager.py:5714
msgid "Periodic task failed to offload instance."
msgstr ""

#: patron/compute/manager.py:5755
#, python-format
msgid "Failed to generate usage audit for instance on host %s"
msgstr ""

#: patron/compute/manager.py:5945
msgid "Periodic sync_power_state task had an error while processing an instance."
msgstr ""

#: patron/compute/manager.py:6069 patron/compute/manager.py:6078
#: patron/compute/manager.py:6117 patron/compute/manager.py:6128
msgid "error during stop() in sync_power_state."
msgstr ""

#: patron/compute/manager.py:6207
#, python-format
msgid "No compute node record for host %s"
msgstr ""

#: patron/compute/manager.py:6494
#, python-format
msgid "Exception while waiting completion of volume snapshots: %s"
msgstr ""

#: patron/compute/monitors/virt/cpu_monitor.py:112
msgid "Not all properties needed are implemented in the compute driver"
msgstr ""

#: patron/conductor/manager.py:122
#, python-format
msgid "Instance update attempted for '%(key)s' on %(instance_uuid)s"
msgstr ""

#: patron/conductor/manager.py:632
#, python-format
msgid ""
"Migration of instance %(instance_id)s to host %(dest)s unexpectedly "
"failed."
msgstr ""

#: patron/conductor/manager.py:784
msgid "Unshelve attempted but an error has occurred"
msgstr ""

#: patron/conductor/manager.py:787
msgid "Unshelve attempted but vm_state not SHELVED or SHELVED_OFFLOADED"
msgstr ""

#: patron/console/xvp.py:124
msgid "Failed to write configuration file"
msgstr ""

#: patron/console/xvp.py:147
#, python-format
msgid "Error starting xvp: %s"
msgstr ""

#: patron/db/api.py:644
msgid "Failed to notify cells of instance destroy"
msgstr ""

#: patron/db/api.py:751 patron/db/api.py:779
msgid "Failed to notify cells of instance update"
msgstr ""

#: patron/db/api.py:1683
msgid "Failed to notify cells of bw_usage update"
msgstr ""

#: patron/db/sqlalchemy/api.py:876
msgid "Failed to update usages bulk deallocating floating IP"
msgstr ""

#: patron/db/sqlalchemy/utils.py:132 patron/db/sqlalchemy/utils.py:136
#: patron/db/sqlalchemy/migrate_repo/versions/216_havana.py:84
#: patron/db/sqlalchemy/migrate_repo/versions/216_havana.py:1103
msgid "Exception while creating table."
msgstr ""

#: patron/db/sqlalchemy/migrate_repo/versions/216_havana.py:111
msgid "Exception while seeding instance_types table"
msgstr ""

#: patron/image/glance.py:261
#, python-format
msgid ""
"When loading the module %(module_str)s the following error occurred: "
"%(ex)s"
msgstr ""

#: patron/image/glance.py:326
#, python-format
msgid "Failed to instantiate the download handler for %(scheme)s"
msgstr ""

#: patron/image/glance.py:347
msgid "Download image error"
msgstr ""

#: patron/image/s3.py:335
#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr ""

#: patron/image/s3.py:352
#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr ""

#: patron/image/s3.py:363
#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr ""

#: patron/image/s3.py:373
#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr ""

#: patron/image/download/__init__.py:41
#, python-format
msgid ""
"%(scheme)s is registered as a module twice. %(module_name)s is not being "
"used."
msgstr ""

#: patron/keymgr/barbican.py:115
#, python-format
msgid "Error creating Barbican client: %s"
msgstr ""

#: patron/keymgr/barbican.py:151
#, python-format
msgid "Error creating key: %s"
msgstr ""

#: patron/keymgr/barbican.py:205
#, python-format
msgid "Error storing key: %s"
msgstr ""

#: patron/keymgr/barbican.py:231
#, python-format
msgid "Error copying key: %s"
msgstr ""

#: patron/keymgr/barbican.py:281
#, python-format
msgid "Error getting secret data: %s"
msgstr ""

#: patron/keymgr/barbican.py:301
#, python-format
msgid "Error getting secret metadata: %s"
msgstr ""

#: patron/keymgr/barbican.py:329
#, python-format
msgid "Error getting key: %s"
msgstr ""

#: patron/keymgr/barbican.py:346
#, python-format
msgid "Error deleting key: %s"
msgstr ""

#: patron/network/base_api.py:52
msgid "Failed storing info cache"
msgstr ""

#: patron/network/driver.py:39
msgid "Network driver option required, but not specified"
msgstr ""

#: patron/network/floating_ips.py:292
msgid "Failed to update usages deallocating floating IP"
msgstr ""

#: patron/network/floating_ips.py:395
#, python-format
msgid "Interface %s not found"
msgstr ""

#: patron/network/linux_net.py:859
#, python-format
msgid "Error deleting conntrack entries for %s"
msgstr ""

#: patron/network/linux_net.py:1115
#, python-format
msgid "kill -HUP dnsmasq threw %s"
msgstr ""

#: patron/network/linux_net.py:1193
#, python-format
msgid "killing radvd threw %s"
msgstr ""

#: patron/network/linux_net.py:1363
#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr ""

#: patron/network/linux_net.py:1425
#, python-format
msgid "Failed removing net device: '%s'"
msgstr ""

#: patron/network/linux_net.py:1436
#, python-format
msgid "Failed removing bridge device: '%s'"
msgstr ""

#: patron/network/manager.py:989
msgid "Failed to update usages deallocating fixed IP"
msgstr ""

#: patron/network/manager.py:1017
#, python-format
msgid "Unable to release %s because vif doesn't exist"
msgstr ""

#: patron/network/manager.py:1024
#, python-format
msgid "Unable to release %s because vif object doesn't exist"
msgstr ""

#: patron/network/manager.py:1038
#, python-format
msgid "Error releasing DHCP for IP %(address)s with MAC %(mac_address)s"
msgstr ""

#: patron/network/neutronv2/api.py:329
#, python-format
msgid "Neutron error creating port on network %s"
msgstr ""

#: patron/network/neutronv2/api.py:367
#, python-format
msgid "Unable to clear device ID for port '%s'"
msgstr ""

#: patron/network/neutronv2/api.py:956
#, python-format
msgid "Failed to access port %s"
msgstr ""

#: patron/network/neutronv2/api.py:1193
#, python-format
msgid "Unable to access floating IP %s"
msgstr ""

#: patron/network/neutronv2/api.py:1327
#, python-format
msgid "Unable to access floating IP %(fixed_ip)s for port %(port_id)s"
msgstr ""

#: patron/network/neutronv2/api.py:1691
#, python-format
msgid "Unable to update host of port %s"
msgstr ""

#: patron/network/security_group/neutron_driver.py:57
#, python-format
msgid "Neutron Error creating security group %s"
msgstr ""

#: patron/network/security_group/neutron_driver.py:78
#, python-format
msgid "Neutron Error updating security group %s"
msgstr ""

#: patron/network/security_group/neutron_driver.py:142
#: patron/network/security_group/neutron_driver.py:145
#: patron/network/security_group/neutron_driver.py:191
#: patron/network/security_group/neutron_driver.py:219
#: patron/network/security_group/neutron_driver.py:290
#, python-format
msgid "Neutron Error: %s"
msgstr ""

#: patron/network/security_group/neutron_driver.py:165
msgid "Neutron Error getting security groups"
msgstr ""

#: patron/network/security_group/neutron_driver.py:211
#, python-format
msgid "Neutron Error getting security group %s"
msgstr ""

#: patron/network/security_group/neutron_driver.py:215
#, python-format
msgid "Neutron Error adding rules to security group %s"
msgstr ""

#: patron/network/security_group/neutron_driver.py:222
#: patron/network/security_group/neutron_driver.py:421
#: patron/network/security_group/neutron_driver.py:428
#: patron/network/security_group/neutron_driver.py:456
#: patron/network/security_group/neutron_driver.py:476
#: patron/network/security_group/neutron_driver.py:483
#: patron/network/security_group/neutron_driver.py:512
msgid "Neutron Error:"
msgstr ""

#: patron/network/security_group/neutron_driver.py:276
#, python-format
msgid "Neutron Error unable to delete %s"
msgstr ""

#: patron/objects/base.py:91
#, python-format
msgid "Error setting %(attr)s"
msgstr ""

#: patron/objects/base.py:300
#, python-format
msgid "Unable to instantiate unregistered object type %(objtype)s"
msgstr ""

#: patron/objects/instance.py:793
#, python-format
msgid "No save handler for %s"
msgstr ""

#: patron/objects/instance_fault.py:90
msgid "Failed to notify cells of instance fault"
msgstr ""

#: patron/objects/instance_info_cache.py:85
msgid "Failed to notify cells of instance info cache update"
msgstr ""

#: patron/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: patron/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: patron/openstack/common/periodic_task.py:228
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: patron/openstack/common/policy.py:564 patron/openstack/common/policy.py:844
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: patron/openstack/common/policy.py:574
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: patron/openstack/common/service.py:272
msgid "Unhandled exception"
msgstr ""

#: patron/pci/stats.py:152
msgid ""
"Failed to allocate PCI devices for instance. Unassigning devices back to "
"pools. This should not happen, since the scheduler should have accurate "
"information, and allocation during claims is controlled via a hold on the"
" compute node semaphore"
msgstr ""

#: patron/pci/utils.py:85 patron/pci/utils.py:101
#, python-format
msgid "PCI device %s not found"
msgstr ""

#: patron/scheduler/scheduler_options.py:69
#, python-format
msgid "Could not stat scheduler options file %(filename)s"
msgstr ""

#: patron/scheduler/scheduler_options.py:78
msgid "Could not decode scheduler options"
msgstr ""

#: patron/scheduler/utils.py:188
#, python-format
msgid "Error from last host: %(last_host)s (node %(last_node)s): %(exc)s"
msgstr ""

#: patron/servicegroup/drivers/db.py:117 patron/servicegroup/drivers/mc.py:103
msgid "Recovered model server connection!"
msgstr ""

#: patron/servicegroup/drivers/db.py:123 patron/servicegroup/drivers/mc.py:109
msgid "model server went away"
msgstr ""

#: patron/servicegroup/drivers/zk.py:129
msgid ""
"Unable to join. It is possible that either another node exists with the "
"same name, or this node just restarted. We will try again in a short "
"while to make sure."
msgstr ""

#: patron/virt/block_device.py:254
#, python-format
msgid "Driver failed to attach volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: patron/virt/driver.py:1258
#, python-format
msgid "Exception dispatching event %(event)s: %(ex)s"
msgstr ""

#: patron/virt/driver.py:1382
msgid "Compute driver option required, but not specified"
msgstr ""

#: patron/virt/driver.py:1392
msgid "Unable to load the virtualization driver"
msgstr ""

#: patron/virt/images.py:114
#, python-format
msgid ""
"%(base)s virtual size %(disk_size)s larger than flavor root disk size "
"%(size)s"
msgstr ""

#: patron/virt/disk/api.py:419
#, python-format
msgid ""
"Failed to mount container filesystem '%(image)s' on '%(target)s': "
"%(errors)s"
msgstr ""

#: patron/virt/disk/api.py:449
msgid "Failed to teardown container filesystem"
msgstr ""

#: patron/virt/disk/api.py:462
msgid "Failed to umount container filesystem"
msgstr ""

#: patron/virt/disk/mount/nbd.py:57
#, python-format
msgid "NBD error - previous umount did not cleanup /var/lock/qemu-nbd-%s."
msgstr ""

#: patron/virt/disk/mount/nbd.py:64
msgid "nbd module not loaded"
msgstr ""

#: patron/virt/hyperv/ioutils.py:46
#, python-format
msgid "Error writing vm console log file from serial console pipe. Error: %s"
msgstr ""

#: patron/virt/hyperv/livemigrationutils.py:42
msgid "Get version 2 connection error"
msgstr ""

#: patron/virt/hyperv/migrationops.py:100
msgid "Cannot cleanup migration files"
msgstr ""

#: patron/virt/hyperv/vmops.py:352
#, python-format
msgid "Requested VM Generation %s is not supported on  this OS."
msgstr ""

#: patron/virt/hyperv/vmops.py:363
#, python-format
msgid "Requested VM Generation %s, but provided VHD instead of VHDX."
msgstr ""

#: patron/virt/hyperv/vmops.py:400 patron/virt/ironic/driver.py:622
#: patron/virt/libvirt/driver.py:2828 patron/virt/vmwareapi/vmops.py:686
#, python-format
msgid "Creating config drive failed with error: %s"
msgstr ""

#: patron/virt/hyperv/vmops.py:458
#, python-format
msgid "Failed to destroy instance: %s"
msgstr ""

#: patron/virt/hyperv/vmops.py:574
#, python-format
msgid "Failed to change vm state of %(instance_name)s to %(req_state)s"
msgstr ""

#: patron/virt/hyperv/volumeops.py:256
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr ""

#: patron/virt/hyperv/volumeops.py:371
#, python-format
msgid "Attach volume failed: %s"
msgstr ""

#: patron/virt/ironic/driver.py:347
#, python-format
msgid ""
"Failed to clean up the parameters on node %(node)s when unprovisioning "
"the instance %(instance)s"
msgstr ""

#: patron/virt/ironic/driver.py:690
#, python-format
msgid ""
"Error preparing deploy for instance %(instance)s on baremetal node "
"%(node)s."
msgstr ""

#: patron/virt/ironic/driver.py:718
#, python-format
msgid "Failed to request Ironic to provision instance %(inst)s: %(reason)s"
msgstr ""

#: patron/virt/ironic/driver.py:733
#, python-format
msgid "Error deploying instance %(instance)s on baremetal node %(node)s."
msgstr ""

#: patron/virt/libvirt/driver.py:664
#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: patron/virt/libvirt/driver.py:746
#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: patron/virt/libvirt/driver.py:773
#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: patron/virt/libvirt/driver.py:1055
#, python-format
msgid "Failed to attach volume at mountpoint: %s"
msgstr ""

#: patron/virt/libvirt/driver.py:1226
msgid "attaching network adapter failed."
msgstr ""

#: patron/virt/libvirt/driver.py:1250
msgid "detaching network adapter failed."
msgstr ""

#: patron/virt/libvirt/driver.py:1571
msgid "Failed to send updated snapshot status to volume service."
msgstr ""

#: patron/virt/libvirt/driver.py:1678
msgid ""
"Unable to create quiesced VM snapshot, attempting again with quiescing "
"disabled."
msgstr ""

#: patron/virt/libvirt/driver.py:1684
msgid "Unable to create VM snapshot, failing volume_snapshot operation."
msgstr ""

#: patron/virt/libvirt/driver.py:1734
msgid ""
"Error occurred during volume_snapshot_create, sending error status to "
"Cinder."
msgstr ""

#: patron/virt/libvirt/driver.py:1956
msgid ""
"Error occurred during volume_snapshot_delete, sending error status to "
"Cinder."
msgstr ""

#: patron/virt/libvirt/driver.py:2533 patron/virt/libvirt/driver.py:2538
#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr ""

#: patron/virt/libvirt/driver.py:2661
#, python-format
msgid "Error injecting data into image %(img_id)s (%(e)s)"
msgstr ""

#: patron/virt/libvirt/driver.py:2921
#, python-format
msgid "Attaching PCI devices %(dev)s to %(dom)s failed."
msgstr ""

#: patron/virt/libvirt/driver.py:4284
#, python-format
msgid "Error defining a domain with XML: %s"
msgstr ""

#: patron/virt/libvirt/driver.py:4288
#, python-format
msgid "Error launching a defined domain with XML: %s"
msgstr ""

#: patron/virt/libvirt/driver.py:4294
#, python-format
msgid "Error enabling hairpin mode with XML: %s"
msgstr ""

#: patron/virt/libvirt/driver.py:4306
#, python-format
msgid "Neutron Reported failure on event %(event)s for instance %(uuid)s"
msgstr ""

#: patron/virt/libvirt/driver.py:5427
#, python-format
msgid "Live Migration failure: %s"
msgstr ""

#: patron/virt/libvirt/driver.py:5580
msgid "Migration operation has aborted"
msgstr ""

#: patron/virt/libvirt/driver.py:5778
#, python-format
msgid "Cannot block migrate instance %s with mapped volumes"
msgstr ""

#: patron/virt/libvirt/driver.py:6629
#, python-format
msgid "Failed to cleanup directory %(target)s: %(e)s"
msgstr ""

#: patron/virt/libvirt/host.py:525
#, python-format
msgid "Connection to libvirt failed: %s"
msgstr ""

#: patron/virt/libvirt/host.py:786 patron/virt/xenapi/host.py:260
#, python-format
msgid ""
"Hostname has changed from %(old)s to %(new)s. A restart is required to "
"take effect."
msgstr ""

#: patron/virt/libvirt/host.py:846
#, python-format
msgid "Error defining a secret with XML: %s"
msgstr ""

#: patron/virt/libvirt/imagebackend.py:248
#, python-format
msgid "Unable to preallocate_images=%(imgs)s at path: %(path)s"
msgstr ""

#: patron/virt/libvirt/imagebackend.py:275
#, python-format
msgid ""
"%(base)s virtual size %(base_size)s larger than flavor root disk size "
"%(size)s"
msgstr ""

#: patron/virt/libvirt/imagebackend.py:602
msgid "Failed to retrieve ephemeral encryption key"
msgstr ""

#: patron/virt/libvirt/imagecache.py:130
#, python-format
msgid "Error reading image info file %(filename)s: %(error)s"
msgstr ""

#: patron/virt/libvirt/imagecache.py:404
#, python-format
msgid "image %(id)s at (%(base_file)s): image verification failed"
msgstr ""

#: patron/virt/libvirt/imagecache.py:463
#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr ""

#: patron/virt/libvirt/lvm.py:220
#, python-format
msgid "ignoring unrecognized volume_clear='%s' value"
msgstr ""

#: patron/virt/libvirt/quobyte.py:59
#, python-format
msgid "The Quobyte volume at %s is still in use."
msgstr ""

#: patron/virt/libvirt/quobyte.py:62
#, python-format
msgid "Couldn't unmount the Quobyte Volume at %s"
msgstr ""

#: patron/virt/libvirt/quobyte.py:78
#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""

#: patron/virt/libvirt/rbd_utils.py:63
#, python-format
msgid "error opening rbd image %s"
msgstr ""

#: patron/virt/libvirt/remotefs.py:63
#, python-format
msgid "Couldn't unmount the share %s"
msgstr ""

#: patron/virt/libvirt/vif.py:487 patron/virt/libvirt/vif.py:514
#: patron/virt/libvirt/vif.py:536 patron/virt/libvirt/vif.py:589
msgid "Failed while plugging vif"
msgstr ""

#: patron/virt/libvirt/vif.py:640 patron/virt/libvirt/vif.py:654
#: patron/virt/libvirt/vif.py:673 patron/virt/libvirt/vif.py:692
#: patron/virt/libvirt/vif.py:721 patron/virt/libvirt/vif.py:741
#: patron/virt/libvirt/vif.py:766
msgid "Failed while unplugging vif"
msgstr ""

#: patron/virt/libvirt/volume.py:173
#, python-format
msgid "Unknown content in connection_info/access_mode: %s"
msgstr ""

#: patron/virt/libvirt/volume.py:922
#, python-format
msgid "Couldn't unmount the NFS share %s"
msgstr ""

#: patron/virt/libvirt/volume.py:1160
#, python-format
msgid "Couldn't unmount the GlusterFS share %s"
msgstr ""

#: patron/virt/vmwareapi/ds_util.py:595
#, python-format
msgid "Unable to retrieve storage policy with name %s"
msgstr ""

#: patron/virt/vmwareapi/images.py:202
msgid "Transfer data failed"
msgstr ""

#: patron/virt/vmwareapi/io_util.py:183
msgid "Read/Write data failed"
msgstr ""

#: patron/virt/vmwareapi/vm_util.py:1285 patron/virt/xenapi/vm_utils.py:319
msgid "Destroy VM failed"
msgstr ""

#: patron/virt/vmwareapi/vmops.py:194
#, python-format
msgid "Extending virtual disk failed with error: %s"
msgstr ""

#: patron/virt/vmwareapi/vmops.py:931
msgid "Destroy instance failed"
msgstr ""

#: patron/virt/vmwareapi/vmops.py:1058
msgid "Unable to access the rescue disk"
msgstr ""

#: patron/virt/vmwareapi/vmops.py:1574
#, python-format
msgid "Attaching network adapter failed. Exception:  %s"
msgstr ""

#: patron/virt/vmwareapi/vmops.py:1614
#, python-format
msgid "Detaching network adapter failed. Exception: %s"
msgstr ""

#: patron/virt/vmwareapi/vmops.py:1686
#, python-format
msgid "Failed to copy cached image %(source)s to %(dest)s for resize: %(error)s"
msgstr ""

#: patron/virt/xenapi/agent.py:112 patron/virt/xenapi/vmops.py:1956
#, python-format
msgid "TIMEOUT: The call to %(method)s timed out. args=%(args)r"
msgstr ""

#: patron/virt/xenapi/agent.py:124 patron/virt/xenapi/vmops.py:1961
#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. "
"args=%(args)r"
msgstr ""

#: patron/virt/xenapi/agent.py:129 patron/virt/xenapi/vmops.py:1966
#, python-format
msgid "The call to %(method)s returned an error: %(e)s. args=%(args)r"
msgstr ""

#: patron/virt/xenapi/agent.py:139
#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. "
"args=%(args)r"
msgstr ""

#: patron/virt/xenapi/agent.py:146
#, python-format
msgid "The agent call to %(method)s returned an an error: %(ret)r. args=%(args)r"
msgstr ""

#: patron/virt/xenapi/driver.py:141
msgid "Failure while cleaning up attached VDIs"
msgstr ""

#: patron/virt/xenapi/host.py:107
#, python-format
msgid "Unable to migrate VM %(vm_ref)s from %(host)s"
msgstr ""

#: patron/virt/xenapi/host.py:363
msgid "Unable to get updated status"
msgstr ""

#: patron/virt/xenapi/host.py:366
#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr ""

#: patron/virt/xenapi/pool.py:65
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on "
"%(host)s"
msgstr ""

#: patron/virt/xenapi/pool.py:177
#, python-format
msgid "Pool-Join failed: %s"
msgstr ""

#: patron/virt/xenapi/pool.py:196
#, python-format
msgid "Pool-eject failed: %s"
msgstr ""

#: patron/virt/xenapi/pool.py:207
#, python-format
msgid "Unable to set up pool: %s."
msgstr ""

#: patron/virt/xenapi/pool.py:218
#, python-format
msgid "Pool-set_name_label failed: %s"
msgstr ""

#: patron/virt/xenapi/vm_utils.py:335
msgid "Shutting down VM (cleanly) failed."
msgstr ""

#: patron/virt/xenapi/vm_utils.py:350
msgid "Shutting down VM (hard) failed"
msgstr ""

#: patron/virt/xenapi/vm_utils.py:403
msgid "Unable to unplug VBD"
msgstr ""

#: patron/virt/xenapi/vm_utils.py:418
msgid "Unable to destroy VBD"
msgstr ""

#: patron/virt/xenapi/vm_utils.py:1437
#, python-format
msgid ""
"Download handler '%(handler)s' raised an exception, falling back to "
"default handler '%(default_handler)s'"
msgstr ""

#: patron/virt/xenapi/vm_utils.py:1493
#, python-format
msgid "Image size %(size)d exceeded flavor allowed size %(allowed_size)d"
msgstr ""

#: patron/virt/xenapi/vm_utils.py:1586
msgid "Failed to fetch glance image"
msgstr ""

#: patron/virt/xenapi/vm_utils.py:1688
msgid "\"Look for the VDIs failed"
msgstr ""

#: patron/virt/xenapi/vm_utils.py:1818
#, python-format
msgid "Unable to parse rrd of %s"
msgstr ""

#: patron/virt/xenapi/vm_utils.py:1902
msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances "
"on. Please check your configuration (e.g. set a default SR for the pool) "
"and/or configure the flag 'sr_matching_filter'."
msgstr ""

#: patron/virt/xenapi/vm_utils.py:1968
#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: "
"%(server)s."
msgstr ""

#: patron/virt/xenapi/vmops.py:952
msgid "_migrate_disk_resizing_down failed. Restoring orig vm"
msgstr ""

#: patron/virt/xenapi/vmops.py:1128
#, python-format
msgid "_migrate_disk_resizing_up failed. Restoring orig vm due_to: %s."
msgstr ""

#: patron/virt/xenapi/vmops.py:1516
#, python-format
msgid "Failed to find an SR for volume %s"
msgstr ""

#: patron/virt/xenapi/vmops.py:1523
#, python-format
msgid "Volume %s is associated with the instance but no SR was found for it"
msgstr ""

#: patron/virt/xenapi/vmops.py:1527
#, python-format
msgid "Failed to forget the SR for volume %s"
msgstr ""

#: patron/virt/xenapi/vmops.py:1737
msgid "Guest does not have a console available"
msgstr ""

#: patron/virt/xenapi/vmops.py:2061
msgid "Migrate Receive failed"
msgstr ""

#: patron/virt/xenapi/vmops.py:2118
msgid "Plugin config_file get_val failed"
msgstr ""

#: patron/virt/xenapi/vmops.py:2206
msgid "Migrate Send failed"
msgstr ""

#: patron/virt/xenapi/volume_utils.py:163
msgid "Unable to introduce VDI on SR"
msgstr ""

#: patron/virt/xenapi/volume_utils.py:178
msgid "Unable to get record of VDI"
msgstr ""

#: patron/virt/xenapi/volume_utils.py:200
msgid "Unable to introduce VDI for SR"
msgstr ""

#: patron/virt/xenapi/volume_utils.py:298
msgid "Unable to find SR from VBD"
msgstr ""

#: patron/virt/xenapi/volume_utils.py:309
msgid "Unable to find SR from VDI"
msgstr ""

#: patron/virt/xenapi/client/session.py:144
msgid "Host is member of a pool, but DB says otherwise"
msgstr ""

#: patron/volume/encryptors/__init__.py:49
#, python-format
msgid "Error instantiating %(provider)s: %(exception)s"
msgstr ""

#: patron/volume/encryptors/__init__.py:64
#, python-format
msgid ""
"Failed to retrieve encryption metadata for volume %(volume_id)s: "
"%(exception)s"
msgstr ""

